root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./.bin/splay serve"
  cmd = 'templ generate && go build -o ./.bin/splay -ldflags="-X main.Commit=$(git rev-parse --short HEAD)" ./main.go'
  delay = 3
  exclude_dir = [".bin", "build", ".tmp", "vendor", "testdata", "app/dist"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "js", "ts", "jsx", "tsx", "css", "scss", "svg"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 1000
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
